### ISSUE TITLE
Age & Server?

### ISSUE THREAD

**Issue by r3pt1s** [Milchreisfan/ContactMe#2]
In deiner Readme steht das du Owner eines Minecraft-Servers bist, und ich wollte mal fragen ob dieser Server einen Discord hat, oder ob es den Server generell noch gibt. Die Andere Frage ist wie alt du bist.
Falls das Alter zu Privat oder so ist einfach Discord falls möglich. -> r3pt1s#4770

**Comment by Milchreisfan** [comment]
Hey mein Minecraft Server habe ich vor kurzer Zeit aus privaten Gründen geschlossen.
