### ISSUE TITLE
Ein Gespräch Privat wäre wichtig.

### ISSUE THREAD

**Issue by Usser2007** [Milchreisfan/ContactMe#3]
Kannst du auf Discord Julian#5001 adden? danke

**Comment by Milchreisfan** [comment]
Über was geht es denn wenn ich fragen darf?

**Comment by Usser2007** [comment]
Es geht um Direkt mehrer sachen. Am besten auf Discord Melden
Julian#5001

Von meinem iPhone gesendet

**Comment by Milchreisfan** [comment]
Ich gebe meine Daten nicht so leicht her, sollte es ein Auftrag sein muss ich diesen derzeit aus privaten Gründen ablehnen.

**Comment by Milchreisfan** [comment]
finished.
